### PR TITLE
Add validator for options marked as required.

### PR DESCRIPTION
**Pull request by saxumVermes**

### CODE REVIEW

**Comment by EclipseGc** [comment]
This feels like maybe I've got something setup incorrectly if we have to do this. No?

**Comment by saxumVermes** [comment]
> This feels like maybe I've got something setup incorrectly if we have to do this. No?

At first I thought it so, but it turned out it's actually the way how it works.

**Comment by saxumVermes** [comment]
Let's keep this the way it was intended to function.

**Comment by EclipseGc** [comment]
Does this mean you've decided we don't need this? I was just slow in getting to it. Let me know what you're thinking tomorrow on scrum.

**Pull request closed without merging**
